name: Run static validation

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run static validation on puppet 5
        uses: puppets-epic-show-theatre/action-pdk-validate@v1
        with:
          puppet-version: "5"

      - name: Run static validation on puppet 6
        uses: puppets-epic-show-theatre/action-pdk-validate@v1
        with:
          puppet-version: "6"

      - name: Run static validation on puppet 7
        uses: puppets-epic-show-theatre/action-pdk-validate@v1
        with:
          puppet-version: "7"
